version = 0.1
[y]
[y.deploy]
[y.deploy.parameters]
stack_name = "menu--app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xo6cwnf450le"
s3_prefix = "menu--app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
